#include <windows.h>
#include <d3dcompiler.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <vector>

bool CompileShaderToHeader(const char* hlslPath, const char* entryPoint, const char* target, const char* outHeaderPath, const char* varName)
{
    FILE* f = fopen(hlslPath, "rb");
    if (!f)
    {
        printf("Error: cannot open input HLSL '%s'\n", hlslPath);
        return false;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);

    std::vector<char> src(sz + 1, 0);
    fread(src.data(), 1, sz, f);
    fclose(f);

    ID3DBlob* blob = nullptr;
    ID3DBlob* err = nullptr;
    UINT flags = D3DCOMPILE_ENABLE_STRICTNESS | D3DCOMPILE_OPTIMIZATION_LEVEL3;

    HRESULT hr = D3DCompile(src.data(), sz, hlslPath, nullptr, D3D_COMPILE_STANDARD_FILE_INCLUDE, entryPoint, target, flags, 0, &blob, &err);
    if (FAILED(hr))
    {
        printf("Compilation failed for %s (%s, %s): 0x%08lx\n", hlslPath, entryPoint, target, hr);
        if (err)
        {
            printf("%s\n", (char*)err->GetBufferPointer());
            err->Release();
        }
        return false;
    }

    FILE* outF = fopen(outHeaderPath, "wb");
    if (!outF)
    {
        printf("Error: cannot open output header '%s'\n", outHeaderPath);
        blob->Release();
        return false;
    }

    fprintf(outF, "// Generated by compile_shaders. Do not edit.\n");
    fprintf(outF, "#pragma once\n\n");
    fprintf(outF, "const unsigned char %s[] = {\n    ", varName);

    const unsigned char* pData = (const unsigned char*)blob->GetBufferPointer();
    size_t dataSize = blob->GetBufferSize();

    for (size_t i = 0; i < dataSize; ++i)
    {
        fprintf(outF, "0x%02X%s", pData[i], (i + 1 < dataSize) ? ", " : "");
        if ((i + 1) % 16 == 0 && i + 1 < dataSize)
        {
            fprintf(outF, "\n    ");
        }
    }

    fprintf(outF, "\n};\n");
    fprintf(outF, "const size_t %s_size = sizeof(%s);\n", varName, varName);
    fclose(outF);

    printf("Compiled %s [%zu bytes] -> %s\n", hlslPath, dataSize, outHeaderPath);
    blob->Release();
    return true;
}

int main(int argc, char** argv)
{
    if (argc < 6)
    {
        printf("Usage: compile_shaders <hlslPath> <entryPoint> <target> <outHeaderPath> <varName>\n");
        return 1;
    }
    return CompileShaderToHeader(argv[1], argv[2], argv[3], argv[4], argv[5]) ? 0 : 1;
}
