import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
THIRD_PARTY_DIR = os.path.join(PROJECT_ROOT, "third_party", "Anime4K")
SHADERS_DIR = os.path.join(SCRIPT_DIR, "Shaders")

UPSTREAM_REPO = "https://github.com/bloc97/Anime4K"
UPSTREAM_COMMIT = "master (v4.0.1)"
LICENSE_NOTICE = "// MIT License - Copyright (c) 2019-2021 bloc97"

def parse_glsl(file_path):
    if not os.path.isfile(file_path):
        print(f"Error: GLSL file not found: {file_path}", file=sys.stderr)
        sys.exit(1)

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    passes = content.split("//!DESC ")
    if len(passes) < 4:
        print(f"Error: Expected at least 4 sections in {file_path}, found {len(passes)}", file=sys.stderr)
        sys.exit(1)

    # Pass 1
    p1 = passes[1]
    p1_muls = re.findall(r'mat4\(([^)]+)\)\s*\*\s*go_0\(([^,]+),\s*([^)]+)\)', p1)
    p1_bias = re.findall(r'vec4\(([^)]+)\)', p1)
    if len(p1_muls) != 9 or len(p1_bias) != 1:
        print(f"Error: Pass 1 validation failed (muls={len(p1_muls)}, bias={len(p1_bias)}) in {file_path}", file=sys.stderr)
        sys.exit(1)

    # Pass 2
    p2 = passes[2]
    p2_pos = re.findall(r'mat4\(([^)]+)\)\s*\*\s*go_0\(([^,]+),\s*([^)]+)\)', p2)
    p2_neg = re.findall(r'mat4\(([^)]+)\)\s*\*\s*go_1\(([^,]+),\s*([^)]+)\)', p2)
    p2_bias = re.findall(r'vec4\(([^)]+)\)', p2)
    if len(p2_pos) != 9 or len(p2_neg) != 9 or len(p2_bias) != 1:
        print(f"Error: Pass 2 validation failed (pos={len(p2_pos)}, neg={len(p2_neg)}, bias={len(p2_bias)}) in {file_path}", file=sys.stderr)
        sys.exit(1)

    # Pass 3
    p3 = passes[3]
    p3_muls = re.findall(r'mat4\(([^)]+)\)\s*\*\s*go_0\(([^,]+),\s*([^)]+)\)', p3)
    p3_bias = re.findall(r'vec4\(([^)]+)\)', p3)
    if len(p3_muls) != 9 or len(p3_bias) != 1:
        print(f"Error: Pass 3 validation failed (muls={len(p3_muls)}, bias={len(p3_bias)}) in {file_path}", file=sys.stderr)
        sys.exit(1)

    return {
        "p1_muls": p1_muls,
        "p1_bias": p1_bias[0].strip(),
        "p2_pos": p2_pos,
        "p2_neg": p2_neg,
        "p2_bias": p2_bias[0].strip(),
        "p3_muls": p3_muls,
        "p3_bias": p3_bias[0].strip(),
    }

def clean_floats(s, count=None):
    parts = [x.strip() for x in s.split(",")]
    if count:
        parts = parts[:count]
    return ", ".join(parts)

def generate_hlsl(data, prefix, title):
    os.makedirs(SHADERS_DIR, exist_ok=True)
    provenance = f"// Generated by Scaler/generate_anime4k.py from {UPSTREAM_REPO} ({UPSTREAM_COMMIT})\n{LICENSE_NOTICE}\n// Zero GPL code. Permissive MIT license.\n\n"

    # --- PASS 1 ---
    p1_lines = []
    p1_lines.append(provenance)
    p1_lines.append(f"// {title} - Pass 1 (3x3 Conv: 3 channels RGB -> 4 channels)")
    p1_lines.append("""Texture2D<float4> InputTex : register(t0);
RWTexture2D<float4> OutputTex : register(u0);

cbuffer ScalerCB : register(b0)
{
    float2 SourceSize;
    float2 SourceOffset;
    float2 TargetSize;
    float2 TargetOffset;
    float2 FullTargetSize;
    float2 SourceTexSize;
};

[numthreads(16, 16, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)SourceSize.x || id.y >= (uint)SourceSize.y) return;

    int2 base = int2(id.xy);
    float3 src[3][3];
    [unroll]
    for (int y = -1; y <= 1; ++y)
    {
        [unroll]
        for (int x = -1; x <= 1; ++x)
        {
            int2 p = clamp(base + int2(x, y), 0, int2(SourceSize) - 1);
            src[x + 1][y + 1] = InputTex.Load(int3(p + int2(SourceOffset), 0)).rgb;
        }
    }
""")
    p1_lines.append(f"    float4 res = float4({data['p1_bias']});")
    for mat_str, x_off, y_off in data['p1_muls']:
        xi = int(float(x_off)) + 1
        yi = int(float(y_off)) + 1
        mat12 = clean_floats(mat_str, 12)
        p1_lines.append(f"    res += mul(src[{xi}][{yi}], float3x4({mat12}));")
    p1_lines.append("\n    OutputTex[id.xy] = res;\n}\n")

    p1_path = os.path.join(SHADERS_DIR, f"{prefix}_Pass1_CS.hlsl")
    with open(p1_path, "w", encoding="utf-8") as f:
        f.write("\n".join(p1_lines))
    print(f"  Wrote: {p1_path}")

    # --- PASS 2 ---
    p2_lines = []
    p2_lines.append(provenance)
    p2_lines.append(f"// {title} - Pass 2 (3x3 Conv: 8 channels (pos/neg split) -> 4 channels)")
    p2_lines.append("""Texture2D<float4> InputTex : register(t0);
RWTexture2D<float4> OutputTex : register(u0);

cbuffer ScalerCB : register(b0)
{
    float2 SourceSize;
    float2 SourceOffset;
    float2 TargetSize;
    float2 TargetOffset;
    float2 FullTargetSize;
    float2 SourceTexSize;
};

[numthreads(16, 16, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)SourceSize.x || id.y >= (uint)SourceSize.y) return;

    int2 base = int2(id.xy);
    float4 srcPos[3][3];
    float4 srcNeg[3][3];
    [unroll]
    for (int y = -1; y <= 1; ++y)
    {
        [unroll]
        for (int x = -1; x <= 1; ++x)
        {
            int2 p = clamp(base + int2(x, y), 0, int2(SourceSize) - 1);
            float4 v = InputTex.Load(int3(p, 0));
            srcPos[x + 1][y + 1] = max(v, 0.0f);
            srcNeg[x + 1][y + 1] = max(-v, 0.0f);
        }
    }
""")
    p2_lines.append(f"    float4 res = float4({data['p2_bias']});")
    for mat_str, x_off, y_off in data['p2_pos']:
        xi = int(float(x_off)) + 1
        yi = int(float(y_off)) + 1
        mat16 = clean_floats(mat_str, 16)
        p2_lines.append(f"    res += mul(srcPos[{xi}][{yi}], float4x4({mat16}));")
    for mat_str, x_off, y_off in data['p2_neg']:
        xi = int(float(x_off)) + 1
        yi = int(float(y_off)) + 1
        mat16 = clean_floats(mat_str, 16)
        p2_lines.append(f"    res += mul(srcNeg[{xi}][{yi}], float4x4({mat16}));")
    p2_lines.append("\n    OutputTex[id.xy] = res;\n}\n")

    p2_path = os.path.join(SHADERS_DIR, f"{prefix}_Pass2_CS.hlsl")
    with open(p2_path, "w", encoding="utf-8") as f:
        f.write("\n".join(p2_lines))
    print(f"  Wrote: {p2_path}")

    # --- PASS 3 ---
    p3_lines = []
    p3_lines.append(provenance)
    p3_lines.append(f"// {title} - Pass 3 (3x3 Conv -> 4 residuals -> 2x Depth-to-Space + Bilinear RGB)")
    p3_lines.append("""Texture2D<float4> InputTex : register(t0);
Texture2D<float4> ConvTex : register(t1);
RWTexture2D<float4> OutputTex2x : register(u0);

SamplerState LinearSampler : register(s1);

cbuffer ScalerCB : register(b0)
{
    float2 SourceSize;
    float2 SourceOffset;
    float2 TargetSize;
    float2 TargetOffset;
    float2 FullTargetSize;
    float2 SourceTexSize;
};

[numthreads(16, 16, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)SourceSize.x || id.y >= (uint)SourceSize.y) return;

    int2 base = int2(id.xy);
    float4 src[3][3];
    [unroll]
    for (int y = -1; y <= 1; ++y)
    {
        [unroll]
        for (int x = -1; x <= 1; ++x)
        {
            int2 p = clamp(base + int2(x, y), 0, int2(SourceSize) - 1);
            src[x + 1][y + 1] = max(ConvTex.Load(int3(p, 0)), 0.0f);
        }
    }
""")
    p3_lines.append(f"    float4 res = float4({data['p3_bias']});")
    for mat_str, x_off, y_off in data['p3_muls']:
        xi = int(float(x_off)) + 1
        yi = int(float(y_off)) + 1
        mat16 = clean_floats(mat_str, 16)
        p3_lines.append(f"    res += mul(src[{xi}][{yi}], float4x4({mat16}));")

    p3_lines.append("""
    float2 invSrcTex = 1.0f / SourceTexSize;
    float2 pBase = float2(id.xy) + SourceOffset;

    float3 in00 = InputTex.SampleLevel(LinearSampler, (pBase + float2(0.25f, 0.25f)) * invSrcTex, 0).rgb;
    float3 in10 = InputTex.SampleLevel(LinearSampler, (pBase + float2(0.75f, 0.25f)) * invSrcTex, 0).rgb;
    float3 in01 = InputTex.SampleLevel(LinearSampler, (pBase + float2(0.25f, 0.75f)) * invSrcTex, 0).rgb;
    float3 in11 = InputTex.SampleLevel(LinearSampler, (pBase + float2(0.75f, 0.75f)) * invSrcTex, 0).rgb;

    OutputTex2x[id.xy * 2 + uint2(0, 0)] = float4(saturate(res.x + in00), 1.0f);
    OutputTex2x[id.xy * 2 + uint2(1, 0)] = float4(saturate(res.y + in10), 1.0f);
    OutputTex2x[id.xy * 2 + uint2(0, 1)] = float4(saturate(res.z + in01), 1.0f);
    OutputTex2x[id.xy * 2 + uint2(1, 1)] = float4(saturate(res.w + in11), 1.0f);
}
""")
    p3_path = os.path.join(SHADERS_DIR, f"{prefix}_Pass3_CS.hlsl")
    with open(p3_path, "w", encoding="utf-8") as f:
        f.write("\n".join(p3_lines))
    print(f"  Wrote: {p3_path}")

def main():
    print("Parsing official Anime4K GLSL sources...")
    glsl_3d = os.path.join(THIRD_PARTY_DIR, "Anime4K_3DGraphics_Upscale_x2_US.glsl")
    glsl_3d_aa = os.path.join(THIRD_PARTY_DIR, "Anime4K_3DGraphics_AA_Upscale_x2_US.glsl")

    data_3d = parse_glsl(glsl_3d)
    print("Generating Anime4K 3D HLSL shaders...")
    generate_hlsl(data_3d, "Anime4K_3D", "Anime4K 3D Upscaler")

    data_3d_aa = parse_glsl(glsl_3d_aa)
    print("Generating Anime4K 3D AA HLSL shaders...")
    generate_hlsl(data_3d_aa, "Anime4K_3D_AA", "Anime4K 3D AA Upscaler")

    print("Strict Anime4K generation completed successfully!")

if __name__ == "__main__":
    main()
