// Generated by Scaler/generate_anime4k.py from https://github.com/bloc97/Anime4K (master (v4.0.1))
// MIT License - Copyright (c) 2019-2021 bloc97
// Zero GPL code. Permissive MIT license.


// Anime4K 3D Upscaler - Pass 1 (3x3 Conv: 3 channels RGB -> 4 channels)
Texture2D<float4> InputTex : register(t0);
RWTexture2D<float4> OutputTex : register(u0);

cbuffer ScalerCB : register(b0)
{
    float2 SourceSize;
    float2 SourceOffset;
    float2 TargetSize;
    float2 TargetOffset;
    float2 FullTargetSize;
    float2 SourceTexSize;
};

[numthreads(16, 16, 1)]
void main(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)SourceSize.x || id.y >= (uint)SourceSize.y) return;

    int2 base = int2(id.xy);
    float3 src[3][3];
    [unroll]
    for (int y = -1; y <= 1; ++y)
    {
        [unroll]
        for (int x = -1; x <= 1; ++x)
        {
            int2 p = clamp(base + int2(x, y), 0, int2(SourceSize) - 1);
            src[x + 1][y + 1] = InputTex.Load(int3(p + int2(SourceOffset), 0)).rgb;
        }
    }

    float4 res = float4(0.0033260486, 0.0027453774, 0.002706769, -0.0022023292);
    res += mul(src[0][0], float3x4(0.020295616, 0.26657984, -0.28531083, 0.041052748, 0.11729335, 0.4042445, -0.5860672, 0.098661005, 0.07756054, 0.32493782, -0.38677853, 0.029859459));
    res += mul(src[0][1], float3x4(-0.28257942, 0.46859467, 0.07703674, -0.05280326, -0.46674755, 0.6592401, 0.28513643, -0.059969574, -0.37685588, 0.54568315, 0.1845521, -0.002367634));
    res += mul(src[0][2], float3x4(-0.14898707, -0.088150576, -0.09723321, 0.48359355, -0.27636692, -0.09316871, -0.15453896, 0.68637407, -0.19012338, -0.13310172, -0.13367014, 0.61284137));
    res += mul(src[1][0], float3x4(0.36225644, 0.14732021, -0.17000826, -0.039856624, 0.50175637, 0.11733988, -0.080232985, -0.059622094, 0.3199943, 0.14199091, -0.08377198, -0.058804136));
    res += mul(src[1][1], float3x4(0.42444956, -0.7508643, 0.77660984, -0.5920436, 0.6205736, -1.1258985, 0.91925675, -0.854362, 0.5576168, -0.84702957, 0.6147012, -0.7004013));
    res += mul(src[1][2], float3x4(0.047896724, -0.018435799, -0.07901341, 0.14234425, 0.12161554, -0.03132901, -0.049536135, 0.16390118, 0.054683182, -0.054823015, -0.019946543, 0.058345634));
    res += mul(src[2][0], float3x4(-0.60845935, -0.0062592463, 0.17769416, 0.00643066, -0.8315386, 0.010405371, 0.227901, 0.054893702, -0.63039875, -0.02128892, 0.20843753, 0.054094747));
    res += mul(src[2][1], float3x4(0.24499738, -0.11924165, -0.16513842, -0.012650152, 0.21676576, -0.14322694, -0.08526706, -0.0122355, 0.26050088, -0.115822464, -0.11147918, -0.018665116));
    res += mul(src[2][2], float3x4(-0.06054074, 0.094478205, -0.23038268, 0.008782032, -0.028404612, 0.22320247, -0.4821615, -0.0055871494, -0.047503285, 0.15098651, -0.26161456, 0.029869653));

    OutputTex[id.xy] = res;
}
